robot:
  _target_: gello.robots.sim_robot.MujocoRobotServer
  xml_path: "third_party/mujoco_menagerie/ufactory_xarm5/xarm5.xml"
  gripper_xml_path: null
  host: "127.0.0.1"
  port: 6001

agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5AF6000708-if00
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5]
    joint_offsets: [
            1.571,
            3.142,
            1.571,
            3.142,
            0,
    ]
    joint_signs: [1, 1, -1, -1, 1]
    gripper_config: [8, 195, 152]
  start_joints: [
            1.571,
            3.142,
            1.571,
            4.712,
            0,
    ]

hz: 30